In [2]:
import numpy as np

In [3]:
#%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [29]:
z = np.ones(20)
z = (z + 1) * 10
z

array([20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
       20., 20., 20., 20., 20., 20., 20.])

In [31]:
z.shape = (5,4)
z

array([[20., 20., 20., 20.],
       [20., 20., 20., 20.],
       [20., 20., 20., 20.],
       [20., 20., 20., 20.],
       [20., 20., 20., 20.]])

In [33]:
lst = [1,2,3,4,5]

In [37]:
arr = np.array(lst)
arr * 1.14

array([1.14, 2.28, 3.42, 4.56, 5.7 ])

In [39]:
type(arr[0])

numpy.int64

In [41]:
arr.astype
arr.shape

(5,)

In [42]:
arr.shape = (5,1)
arr.shape

(5, 1)

In [53]:
np.linspace(0, 50, 11)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [1]:

import time
import numpy as np

# Using list
lst = list(range(10_000_000))
start = time.time()
lst = [x * 2 for x in lst]
print("List time:", time.time() - start)

# Using NumPy array
arr = np.arange(10_000_000)
start = time.time()
arr = arr * 2
print("Array time:", time.time() - start)



List time: 0.9641032218933105
Array time: 0.04732322692871094
