# NumPy Tutorial

Welcome to the **NumPy Tutorial**! NumPy is a powerful Python library for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

### What you'll learn:
- Creating arrays
- Array operations
- Indexing and slicing
- Broadcasting
- Common functions

Let's get started!

In [1]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.3.5


## Creating Arrays
NumPy arrays can be created in several ways:
- From a Python list using `np.array()`
- Using built-in functions like `np.zeros()`, `np.ones()`, `np.arange()`, and `np.linspace()`

### Example:

In [2]:
# Creating arrays
arr1 = np.array([1, 2, 3, 4])
print("Array from list:", arr1)

arr2 = np.zeros((2, 3)) #(n, m) → 2D array with n rows and m columns.
print("Zeros array:", arr2)

arr3 = np.ones((3,)) # (n,) → 1D array of length n.
print("Ones array:", arr3)

arr4 = np.arange(0, 10, 2)
print("Arange array:", arr4)

arr5 = np.linspace(0, 1, 5)
print("Linspace array:", arr5)

Array from list: [1 2 3 4]
Zeros array: [[0. 0. 0.]
 [0. 0. 0.]]
Ones array: [1. 1. 1.]
Arange array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


### Practice Exercise:
Create a 3x3 array of ones and a 1D array of numbers from 10 to 50 with a step of 5.

In [3]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
arr1d = np.arange(10, 51, 5) #since the exercise indicate the step, the arange will be the best choice
arr1d

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

## Array Operations
You can perform element-wise operations on NumPy arrays:
- Addition, subtraction, multiplication, division
- Mathematical functions like `np.sqrt()`, `np.exp()`, `np.sin()`

### Example:

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Square root of a:", np.sqrt(a))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Square root of a: [1.         1.41421356 1.73205081]


### Practice Exercise:
Create two arrays and perform addition, subtraction, and find the sine of the first array.

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Sine of a:", np.sin(a))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Sine of a: [0.84147098 0.90929743 0.14112001]


## Indexing & Slicing
Access elements using indices and slices:
- `arr[i]` for single element
- `arr[start:end]` for slicing

### Example:

In [7]:
arr = np.arange(10)
print("Original array:", arr)
print("First element:", arr[0])
print("Slice 2 to 5:", arr[2:6])
print("Reverse:", arr[::-1])

Original array: [0 1 2 3 4 5 6 7 8 9]
First element: 0
Slice 2 to 5: [2 3 4 5]
Reverse: [9 8 7 6 5 4 3 2 1 0]


### Practice Exercise:
Create an array of numbers from 1 to 20 and extract:
- The first 5 elements
- Every second element
- The last 5 elements in reverse order.

In [8]:
arr = np.arange(1,21)
print("Original array:", arr)
print("First 5 elements:", arr[:5])
print("Every second element:", arr[::2])
print("last 5 elements in reverse order:", arr[-1:-6:-1])

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
First 5 elements: [1 2 3 4 5]
Every second element: [ 1  3  5  7  9 11 13 15 17 19]
last 5 elements in reverse order: [20 19 18 17 16]


## Broadcasting
Broadcasting allows NumPy to perform operations on arrays of different shapes.

### Example:

In [9]:
a = np.array([1, 2, 3])
b = 2
print("Array:", a)
print("Scalar:", b)
print("Result of broadcasting (a * b):", a * b)

Array: [1 2 3]
Scalar: 2
Result of broadcasting (a * b): [2 4 6]


### Practice Exercise:
Create a 2D array and add a 1D array to it using broadcasting.

In [10]:

import numpy as np

# Create a 2D array (3 rows, 3 columns)
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Create a 1D array (length 3)
arr1d = np.array([10, 20, 30])

# Add using broadcasting
result = arr2d + arr1d

print("2D array:\n", arr2d)
print("1D array:", arr1d)
print("Result after broadcasting:\n", result)

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1D array: [10 20 30]
Result after broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [11]:
arr2d = np.array([[2,4],[6,8]])
arr1d = np.array([10,20])

result = arr2d + arr1d
print(result)

[[12 24]
 [16 28]]


## Common Functions
NumPy provides many useful functions:
- `np.mean()`, `np.sum()`, `np.max()`, `np.min()`, `np.std()`

### Example:

In [12]:

arr = np.arange(1, 6)
print("Array:", arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Standard Deviation:", np.std(arr))

Array: [1 2 3 4 5]
Sum: 15
Mean: 3.0
Max: 5
Standard Deviation: 1.4142135623730951


### Practice Exercise:
Create an array of 10 random numbers and find its mean, max, and standard deviation.

In [13]:
from numpy.random import default_rng

In [16]:
rng = np.random.default_rng(10)
arr = rng.random(10)
print("Array:", arr)
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Standard Deviation:", np.std(arr))

Array: [0.95600171 0.20768181 0.82844489 0.14928212 0.51280462 0.1359196
 0.68903648 0.84174772 0.425509   0.956926  ]
Mean: 0.5703353953473499
Max: 0.9569260034533662
Standard Deviation: 0.31214915498974855
