In [2]:
import numpy as np

In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [29]:
z = np.ones(20)
z = (z + 1) * 10
z

array([20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20., 20.,
       20., 20., 20., 20., 20., 20., 20.])

In [31]:
z.shape = (5,4)
z

array([[20., 20., 20., 20.],
       [20., 20., 20., 20.],
       [20., 20., 20., 20.],
       [20., 20., 20., 20.],
       [20., 20., 20., 20.]])

In [33]:
lst = [1,2,3,4,5]

In [37]:
arr = np.array(lst)
arr * 1.14

array([1.14, 2.28, 3.42, 4.56, 5.7 ])

In [39]:
type(arr[0])

numpy.int64

In [41]:
arr.astype
arr.shape

(5,)

In [42]:
arr.shape = (5,1)
arr.shape

(5, 1)

In [53]:
np.linspace(0, 50, 11)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

Type:        ndarray
String form:
[[1]
 [2]
 [3]
 [4]
 [5]]
Length:      5
File:        c:\users\biauser\miniconda3\envs\analyst-lab\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : dat