# Complete Pandas & NumPy Tutorial
This notebook covers four sections:
1. **NumPy Basics**
2. **Pandas Series**
3. **Pandas DataFrame**
4. **Aggregating & Reshaping DataFrames**

Each section includes explanations, code examples, expected outputs, and challenges with solutions.

## 1. NumPy Basics
NumPy is a fundamental package for scientific computing in Python.

In [5]:
import sys
import numpy as np
import pandas as pd

print('Python version:', sys.version)
print('NumPy version:', np.__version__)
print(f'Pandas version:, {pd.__version__}\n\nRun Time:')

Python version: 3.11.14 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 18:30:03) [MSC v.1929 64 bit (AMD64)]
NumPy version: 2.3.5
Pandas version:, 2.3.3

\Run Time:


**Expected Output:**
- Python version info
- NumPy version
- Pandas version

### NumPy Arrays and Properties

In [20]:
arr = np.array([1, 2, 3, 4])
print('Array:', arr)
print('Shape:', arr.shape)
print('Data type:', arr.dtype)
print('Size:', arr.size)
twoD = arr.reshape(4,1)
twoD.ndim, twoD

Array: [1 2 3 4]
Shape: (4,)
Data type: int64
Size: 4


(2,
 array([[1],
        [2],
        [3],
        [4]]))

**Expected Output:**
```
Array: [1 2 3 4]
Shape: (4,)
Data type: int64
```

### Challenge: Array Basics

In [31]:
# Create a 2D array and print its shape and size
challenge_arr = np.array([[1, 2], [3, 4]])
print('Shape:', challenge_arr.shape)
print('Size:', challenge_arr.size)
serChallenge = pd.DataFrame(challenge_arr)
print(' ')
serChallenge.info(), serChallenge.describe()

Shape: (2, 2)
Size: 4
 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2 non-null      int64
 1   1       2 non-null      int64
dtypes: int64(2)
memory usage: 164.0 bytes


(None,
               0         1
 count  2.000000  2.000000
 mean   2.000000  3.000000
 std    1.414214  1.414214
 min    1.000000  2.000000
 25%    1.500000  2.500000
 50%    2.000000  3.000000
 75%    2.500000  3.500000
 max    3.000000  4.000000)

**Expected Output:**
```
Shape: (2, 2)
Size: 4
```

### Array Creation and Random Numbers

In [32]:
zeros = np.zeros((2, 3))  # could also use lists
ones = np.ones((2, 3))
arange_arr = np.arange(0, 10, 2)
rand_arr = np.random.rand(3, 3)

print('Zeros:\n', zeros)
print('Ones:\n', ones)
print('Arange:\n', arange_arr)
print('Random:\n', rand_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Arange:
 [0 2 4 6 8]
Random:
 [[0.53030007 0.5816894  0.09921016]
 [0.06077332 0.33457331 0.49302838]
 [0.70862371 0.10443561 0.46587236]]


**Expected Output:**
- 2x3 zeros array
- 2x3 ones array
- [0 2 4 6 8]
- 3x3 random floats

### Indexing, Slicing, and Operations

In [34]:
arr2 = np.array([10, 20, 30, 40, 50])
print(arr2[1:4])
print(arr2[::-1])  # start : stop : step

# Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)

[20 30 40]
[50 40 30 20 10]
[5 7 9]
[ 4 10 18]


In [46]:
print(arr2[-1::-1])

[50 40 30 20 10]


**Expected Output:**
- Slice: [20 30 40]
- Reverse: [50 40 30 20 10]
- Addition: [5 7 9]
- Multiplication: [4 10 18]

### Filtering and where()

In [52]:
arr3 = np.array([10, 15, 20, 25])
print(arr3>15)
print(arr3[arr3 > 15])
print(np.where(arr3 > 15, 0, arr3))  # element-wise operation  -->  where(condition, True val, False val)

[False False  True  True]
[20 25]
[10 15  0  0]


**Expected Output:**
- Filtered: [20 25]
- Where replaced: [10 15 0 0]

### Aggregation and Sorting

In [55]:
print(arr3.sum())
print(arr3.mean())
unsorted_arr = np.array([3, 1, 4, 2])
print(np.sort(unsorted_arr))

70
17.5
[1 2 3 4]


**Expected Output:**
- Sum: 70
- Mean: 17.5
- Sorted: [1 2 3 4]

### Broadcasting

In [60]:
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])
#print(a + b)
a.shape

(3,)

**Expected Output:**
```
[[11 12 13]
 [21 22 23]
 [31 32 33]]
```

## 2. Pandas Series
### Series Basics

In [68]:
s = pd.Series([10, 20, 30, 40])
#s= pd.DataFrame(s) #become two dim array
print(s)

0    10
1    20
2    30
3    40
dtype: int64


**Expected Output:**
```
0    10
1    20
2    30
3    40
dtype: int64
```

### Data Types and Conversion

In [71]:
print(f'{s.dtype}\n*******')
s_float = s.astype(float)
print(s_float.dtype)

int64
*******
float64


**Expected Output:**
- int64
- Series with float values

### Indexing and loc/iloc

In [74]:
s_custom = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(s_custom.loc['b': 'c'])
print('******')
print(s_custom.iloc[-2:])

b    20
c    30
dtype: int64
******
b    20
c    30
dtype: int64


**Expected Output:**
- 20
- 20

### Filtering and Sorting

In [75]:
print(s[s > 20])
print(s.sort_values(ascending=False))

2    30
3    40
dtype: int64
3    40
2    30
1    20
0    10
dtype: int64


**Expected Output:**
- Filtered: 30, 40
- Sorted descending

## 3. Pandas DataFrame
### DataFrame Basics

In [76]:
data = {'Name': ['Alice', 'Bob', 'Charlie'], 
        'Age': [25, 30, 35], 
        'Salary': [50000, 60000, 70000]}
df = pd.DataFrame(data)
print(df)

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000


**Expected Output:**
```
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
```

In [80]:
list(np.array(df['Name']))

['Alice', 'Bob', 'Charlie']

### Exploring DataFrames

In [83]:
print(df.head())
print(df.info())
print(df.describe())

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   Salary  3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None
        Age   Salary
count   3.0      3.0
mean   30.0  60000.0
std     5.0  10000.0
min    25.0  50000.0
25%    27.5  55000.0
50%    30.0  60000.0
75%    32.5  65000.0
max    35.0  70000.0


**Expected Output:**
- First rows
- Info summary
- Statistical summary

### Filtering and Sorting

In [85]:
print(df[df['Age'] > 28])
print(' ')
print(df.sort_values(by='Salary'))

      Name  Age  Salary
1      Bob   30   60000
2  Charlie   35   70000
 
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000


**Expected Output:**
- Rows with Age > 28
- Sorted by Salary ascending

## 4. Aggregating & Reshaping DataFrames
### groupby() Basics

In [95]:
group_df = pd.DataFrame({'Dept': ['HR','HR','IT','IT', 'HR'], 'Salary':[50000,60000,70000,80000,250000]})
group_df
print(group_df.groupby('Dept')['Salary'].mean())

Dept
HR    120000.0
IT     75000.0
Name: Salary, dtype: float64


**Expected Output:**
```
Dept
HR    55000
IT    75000
Name: Salary, dtype: int64
```

### Pivot Table

In [101]:
pivot_df = pd.DataFrame({'Dept':['HR','HR','IT','IT'], 'Year':[2024,2025,2024,2025], 'Salary':[50000,60000,70000,80000]})
print(f'{pivot_df}\n*********************')
print(pd.pivot_table(pivot_df, values='Salary', index='Dept', columns='Year', aggfunc='mean'))

  Dept  Year  Salary
0   HR  2024   50000
1   HR  2025   60000
2   IT  2024   70000
3   IT  2025   80000
*********************
Year     2024     2025
Dept                  
HR    50000.0  60000.0
IT    70000.0  80000.0


**Expected Output:**
```
Year   2024   2025
Dept               
HR   50000  60000
IT   70000  80000
```