In [1]:
import numpy as np

In [2]:
data = np.random.rand(2,3,4) # Generates random numbers and Each number is a float between 0 and 1

zeros = np.zeros((2,2,2))
full = np.full((2,2,2),7)
ones = np.ones((2,2,2))

In [3]:
data

array([[[0.48361922, 0.31953328, 0.61978261, 0.05659482],
        [0.13711926, 0.90441376, 0.97140133, 0.65157363],
        [0.19556312, 0.46800286, 0.99930288, 0.13660159]],

       [[0.74443629, 0.59465919, 0.56384405, 0.51891251],
        [0.99657281, 0.11190711, 0.14883058, 0.79551539],
        [0.20881444, 0.67267738, 0.21108119, 0.13363585]]])

In [4]:
#The numbers (2, 3, 4) define the shape of the array — in other words, how many dimensions and how big each one is.
'''
This creates a 3‑dimensional array:
2>> two blocks
3>> each block has 3 rows
4>> each row has 4 columns
'''

'\nThis creates a 3‑dimensional array:\n2>> two blocks\n3>> each block has 3 rows\n4>> each row has 4 columns\n'

In [5]:
data.shape

(2, 3, 4)

In [6]:
data.ndim

3

In [7]:
data[0] # One full 3×4 block

array([[0.48361922, 0.31953328, 0.61978261, 0.05659482],
       [0.13711926, 0.90441376, 0.97140133, 0.65157363],
       [0.19556312, 0.46800286, 0.99930288, 0.13660159]])

In [8]:
data[0,1] #One row

array([0.13711926, 0.90441376, 0.97140133, 0.65157363])

In [9]:
data[0,1,2] #One single value

np.float64(0.9714013274029556)

In [10]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [11]:
full # np.full(shape, fill_value, dtype=None*) creates a NumPy array of a given shape and fills every element with the same constant fill_value.
# * dtype was not mentioned

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [12]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [13]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [14]:
type(arr)

numpy.ndarray

In [15]:
shape = data.shape
shape

(2, 3, 4)

In [16]:
size = data.size
size

24

In [17]:
types = data.dtype
types

dtype('float64')

In [18]:
arr = data[0]
arr

array([[0.48361922, 0.31953328, 0.61978261, 0.05659482],
       [0.13711926, 0.90441376, 0.97140133, 0.65157363],
       [0.19556312, 0.46800286, 0.99930288, 0.13660159]])

In [19]:
slicer = data[0][0:2]
slicer

array([[0.48361922, 0.31953328, 0.61978261, 0.05659482],
       [0.13711926, 0.90441376, 0.97140133, 0.65157363]])

In [20]:
reverse = data[-1]
reverse

array([[0.74443629, 0.59465919, 0.56384405, 0.51891251],
       [0.99657281, 0.11190711, 0.14883058, 0.79551539],
       [0.20881444, 0.67267738, 0.21108119, 0.13363585]])

In [21]:
singvalue = data[0][0][0]
singvalue

np.float64(0.483619218602125)

In [22]:
data [0,0,0] = 700
data

array([[[7.00000000e+02, 3.19533279e-01, 6.19782606e-01, 5.65948216e-02],
        [1.37119257e-01, 9.04413760e-01, 9.71401327e-01, 6.51573633e-01],
        [1.95563123e-01, 4.68002856e-01, 9.99302881e-01, 1.36601587e-01]],

       [[7.44436291e-01, 5.94659190e-01, 5.63844047e-01, 5.18912514e-01],
        [9.96572807e-01, 1.11907109e-01, 1.48830575e-01, 7.95515386e-01],
        [2.08814445e-01, 6.72677380e-01, 2.11081192e-01, 1.33635848e-01]]])

In [23]:

print(data[0, 0, 0])   # 700
print(data[0, 0, :])   # [700   0   0   0]
print(data[0, :, :].shape)  # (3, 4)  -> this is the first "block"


700.0
[7.00000000e+02 3.19533279e-01 6.19782606e-01 5.65948216e-02]
(3, 4)


In [24]:
data[:, 0, 0]

array([700.        ,   0.74443629])

In [25]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [26]:
list1

array([0.06600872, 0.98243365, 0.10179955, 0.63356371, 0.66082565,
       0.84733738, 0.48098573, 0.49570794, 0.0244244 , 0.42975644])

In [27]:
list3 = np.random.random((2,1,4))
list3

array([[[0.00180677, 0.07781344, 0.36689765, 0.88841903]],

       [[0.44803643, 0.6005062 , 0.01902829, 0.54431565]]])

In [28]:
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [29]:
dot #multiple each value together and agreagate the result

np.float64(2.8285855232196653)

In [30]:
#Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [31]:
exp

array([ 7.3890561 , 20.08553692])

In [32]:
data.sort()
data

array([[[5.65948216e-02, 3.19533279e-01, 6.19782606e-01, 7.00000000e+02],
        [1.37119257e-01, 6.51573633e-01, 9.04413760e-01, 9.71401327e-01],
        [1.36601587e-01, 1.95563123e-01, 4.68002856e-01, 9.99302881e-01]],

       [[5.18912514e-01, 5.63844047e-01, 5.94659190e-01, 7.44436291e-01],
        [1.11907109e-01, 1.48830575e-01, 7.95515386e-01, 9.96572807e-01],
        [1.33635848e-01, 2.08814445e-01, 2.11081192e-01, 6.72677380e-01]]])

In [33]:
print(data.shape)

(2, 3, 4)


In [34]:
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [35]:
data

array([[[5.65948216e-02, 3.19533279e-01, 6.19782606e-01, 7.00000000e+02,
         1.37119257e-01, 6.51573633e-01],
        [9.04413760e-01, 9.71401327e-01, 1.36601587e-01, 1.95563123e-01,
         4.68002856e-01, 9.99302881e-01]],

       [[5.18912514e-01, 5.63844047e-01, 5.94659190e-01, 7.44436291e-01,
         1.11907109e-01, 1.48830575e-01],
        [7.95515386e-01, 9.96572807e-01, 1.33635848e-01, 2.08814445e-01,
         2.11081192e-01, 6.72677380e-01]]])

In [36]:
zeroes = np.zeros((8))
#print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [37]:
zeroes = np.insert(zeroes, 2,1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


In [38]:
data

array([[[5.65948216e-02, 3.19533279e-01, 6.19782606e-01, 7.00000000e+02,
         1.37119257e-01, 6.51573633e-01],
        [9.04413760e-01, 9.71401327e-01, 1.36601587e-01, 1.95563123e-01,
         4.68002856e-01, 9.99302881e-01]],

       [[5.18912514e-01, 5.63844047e-01, 5.94659190e-01, 7.44436291e-01,
         1.11907109e-01, 1.48830575e-01],
        [7.95515386e-01, 9.96572807e-01, 1.33635848e-01, 2.08814445e-01,
         2.11081192e-01, 6.72677380e-01]]])

In [39]:
data.shape

(2, 2, 6)

In [40]:
newdata = np.delete(data, 0, axis=1)
newdata

array([[[0.90441376, 0.97140133, 0.13660159, 0.19556312, 0.46800286,
         0.99930288]],

       [[0.79551539, 0.99657281, 0.13363585, 0.20881444, 0.21108119,
         0.67267738]]])

In [41]:
newdata.shape

(2, 1, 6)

In [42]:
np.save("new array", data)

In [43]:
test = np.load("new array.npy")
test

array([[[5.65948216e-02, 3.19533279e-01, 6.19782606e-01, 7.00000000e+02,
         1.37119257e-01, 6.51573633e-01],
        [9.04413760e-01, 9.71401327e-01, 1.36601587e-01, 1.95563123e-01,
         4.68002856e-01, 9.99302881e-01]],

       [[5.18912514e-01, 5.63844047e-01, 5.94659190e-01, 7.44436291e-01,
         1.11907109e-01, 1.48830575e-01],
        [7.95515386e-01, 9.96572807e-01, 1.33635848e-01, 2.08814445e-01,
         2.11081192e-01, 6.72677380e-01]]])

## Complement Numpy basics

In [44]:

import numpy as np
np.random.seed(7)

# Small, deterministic arrays to make results readable
A = np.array([[ 2, -1,  5,  0],
              [ 3,  8, -2,  1],
              [ 0,  4,  9, -3]])

B = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90,100,110,120]])

C = np.array([1.5, 0.5, -2.0, 3.0])      # shape (4,)
D = np.array([[1.0],[2.0],[3.0]])        # shape (3,1) for broadcasting demos

1) Boolean mask: basic filter
Goal: Keep only values in A that are > 0.

Print: the boolean mask and the filtered 1‑D result.

In [45]:
mask = A > 0
pos = A[mask]
print(mask)
print(pos)

[[ True False  True False]
 [ True  True False  True]
 [False  True  True False]]
[2 5 3 8 1 4 9]



2️⃣ Conditional update with a mask
Goal: Replace negative values in A with 0.


In [46]:

A2 = A.copy()
A2[A2 < 0] = 0
print(A2)


[[2 0 5 0]
 [3 8 0 1]
 [0 4 9 0]]



3️⃣ Compound conditions
Goal: Values between 1 and 5 (inclusive) OR equal to 8.


In [47]:
cond = ((A >= 1) & (A <= 5)) | (A == 8)
print(cond)

[[ True False  True False]
 [ True  True False  True]
 [False  True False False]]



4️⃣ Masking rows
Goal: Rows where all values are ≥ 0.


In [48]:
row_mask = (A>=0).all(axis=1)
print(row_mask)

[False False False]



5️⃣ Broadcasting (row‑wise addition)
Goal: Add vector C to each row of B.


In [49]:
B_plus_C = B+C
print(B_plus_C.shape)
print(B_plus_C)

(3, 4)
[[ 11.5  20.5  28.   43. ]
 [ 51.5  60.5  68.   83. ]
 [ 91.5 100.5 108.  123. ]]



6️⃣ Broadcasting (column‑wise scaling)
Goal: Multiply each row of A by 1, 2, and 3.


In [51]:
scaled = A*D
print(scaled)

[[ 2. -1.  5.  0.]
 [ 6. 16. -4.  2.]
 [ 0. 12. 27. -9.]]


7. Axis basics
Goal: Column mean vc row mean for B

In [54]:
print(B.mean(axis=0))
print(B.mean(axis=1))

[50. 60. 70. 80.]
[ 25.  65. 105.]


8. Column Stardardization (z-score)

In [56]:
mu = B.mean(axis=0, keepdims=True)
sd = B.std(axis=0, keepdims=True)
Z = (B-mu)/sd
print(Z.mean(axis=0))

[0. 0. 0. 0.]


9. Weighted sum per row

In [59]:
w = np.array([0.1,0.2,0.3,0.4])
ws = (B*w).sum(axis=1)
print(ws)

[ 30.  70. 110.]


In [61]:
idx_sorted = np.argsort(B, axis=0)
top2_idx = idx_sorted[-2:]
print(top2_idx)

[[1 1 1 1]
 [2 2 2 2]]


In [63]:
neg_per_col = (A<0).any(axis=0)
print(neg_per_col)

[False  True  True  True]


In [65]:
A3 = A.copy().astype(float)
mu= A3.mean(axis=0, keepdims=True)
sd = A3.std(axis=0, keepdims=True)
z = (A3 - mu)/sd
mask = np.abs(z)>1.5
col_medians = np.median(A3, axis=0, keepdims=True)
A3[mask] = col_medians.repeat(A3.shape[0], axis=0)[mask]
print(A3)

[[ 2. -1.  5.  0.]
 [ 3.  8. -2.  1.]
 [ 0.  4.  9. -3.]]
