# NumPy for Beginners — Enhanced Curriculum

## Table of Contents
1. Introduction to NumPy
2. Installing and Importing NumPy
3. Creating Arrays
4. Array Attributes and Basic Operations
5. Indexing and Slicing
6. Reshaping and Resizing
7. Broadcasting
8. Mathematical Operations
9. Aggregation Functions
10. Working with Random Numbers
11. Saving and Loading Arrays
12. Final Mini-Project

# Section 1 — Introduction to NumPy

## Learning Objectives
- Understand what NumPy is and why it’s important.
- Learn the key features of NumPy for numerical computing.

### Explanation
NumPy is a Python library for numerical computing. It provides:
- **ndarray**: A powerful n-dimensional array object.
- Efficient operations for linear algebra, statistics, and more.

Why use NumPy?
- Faster than Python lists for numerical tasks.
- Supports vectorized operations.

In [1]:
# Example: Import NumPy and check version
import numpy as np
print(np.__version__)

2.3.5


### Practice Exercises
1. What is NumPy?
2. Why is it faster than Python lists?
3. Import NumPy and print its version.

# Section 2 — Installing and Importing NumPy

## Learning Objectives
- Install NumPy using pip.
- Import NumPy and verify installation.

### Explanation
To install NumPy:
```
pip install numpy
```
To import:
```python
import numpy as np
```

# Section 3 — Creating Arrays

## Learning Objectives
- Create arrays using np.array(), np.zeros(), np.ones(), np.arange().

In [2]:
# Example: Create arrays
arr = np.array([1, 2, 3])
print(arr)

zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
range_arr = np.arange(0, 10, 2)
print(zeros)
print(ones)
print(range_arr)

[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]


# Section 4 — Array Attributes and Basic Operations

## Learning Objectives
- Understand shape, size, dtype.
- Perform element-wise operations.

In [3]:
# Example: Array attributes
print(arr.shape)
print(arr.dtype)

# Element-wise operations
print(arr + 10)
print(arr * 2)

(3,)
int64
[11 12 13]
[2 4 6]


# Section 5 — Indexing and Slicing

## Learning Objectives
- Access elements using indices.
- Slice arrays.

In [4]:
# Example: Indexing and slicing
print(arr[0])
print(arr[1:3])

1
[2 3]


# Section 6 — Reshaping and Resizing

## Learning Objectives
- Reshape arrays using .reshape().

In [5]:
# Example: Reshape
reshaped = np.arange(12).reshape(3, 4)
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Section 7 — Broadcasting

## Learning Objectives
- Understand broadcasting rules.

In [6]:
# Example: Broadcasting
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])
print(a + b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Section 8 — Mathematical Operations

## Learning Objectives
- Use np.add(), np.subtract(), np.multiply(), np.divide().

In [7]:
# Example: Math operations
print(np.add(a, 5))
print(np.multiply(a, 2))

[6 7 8]
[2 4 6]


# Section 9 — Aggregation Functions

## Learning Objectives
- Use np.sum(), np.mean(), np.max(), np.min().

In [8]:
# Example: Aggregations
print(np.sum(a))
print(np.mean(a))
print(np.max(a))

6
2.0
3


# Section 10 — Working with Random Numbers

## Learning Objectives
- Generate random numbers using np.random.

In [9]:
# Example: Random numbers
rand_arr = np.random.rand(3, 3)
print(rand_arr)

[[0.82313693 0.03899271 0.22664613]
 [0.03026074 0.65396821 0.02220731]
 [0.69919666 0.8902681  0.83005847]]


# Section 11 — Saving and Loading Arrays

## Learning Objectives
- Save arrays using np.save().
- Load arrays using np.load().

In [10]:
# Example: Save and load
np.save('array.npy', arr)
loaded = np.load('array.npy')
print(loaded)

[1 2 3]


# Section 12 — Final Mini-Project

## Objective
Perform the following:
- Create a large random array.
- Compute mean, max, min.
- Reshape and apply broadcasting.
- Save and reload the array.

In [14]:
large_arr = np.random.rand(10,5)
large_arr

array([[0.77593154, 0.17374899, 0.55938859, 0.84156552, 0.30386606],
       [0.40741942, 0.39576405, 0.78732687, 0.5090837 , 0.39716788],
       [0.42414996, 0.55385691, 0.70906221, 0.9196071 , 0.54156617],
       [0.24155025, 0.34665917, 0.18893802, 0.78543608, 0.52568713],
       [0.27432479, 0.42146211, 0.64754249, 0.56220873, 0.11005708],
       [0.20495465, 0.57370082, 0.14142352, 0.54431487, 0.30107074],
       [0.57577664, 0.8648688 , 0.86479704, 0.24391579, 0.27819818],
       [0.04813894, 0.47144927, 0.91232093, 0.66874716, 0.48145473],
       [0.05648672, 0.35869393, 0.13573034, 0.42232871, 0.30026261],
       [0.69995562, 0.79290624, 0.45508966, 0.3965676 , 0.72233924]])

In [19]:
print(np.mean(large_arr))
print(np.max(large_arr))
print(np.min(large_arr))

0.478377271729185
0.9196070985361248
0.048138937281201555


In [21]:
arr_shaped = large_arr.reshape(5,10)
arr_shaped

array([[0.77593154, 0.17374899, 0.55938859, 0.84156552, 0.30386606,
        0.40741942, 0.39576405, 0.78732687, 0.5090837 , 0.39716788],
       [0.42414996, 0.55385691, 0.70906221, 0.9196071 , 0.54156617,
        0.24155025, 0.34665917, 0.18893802, 0.78543608, 0.52568713],
       [0.27432479, 0.42146211, 0.64754249, 0.56220873, 0.11005708,
        0.20495465, 0.57370082, 0.14142352, 0.54431487, 0.30107074],
       [0.57577664, 0.8648688 , 0.86479704, 0.24391579, 0.27819818,
        0.04813894, 0.47144927, 0.91232093, 0.66874716, 0.48145473],
       [0.05648672, 0.35869393, 0.13573034, 0.42232871, 0.30026261,
        0.69995562, 0.79290624, 0.45508966, 0.3965676 , 0.72233924]])

In [24]:
Broad = arr_shaped * 2
Broad

array([[1.55186308, 0.34749797, 1.11877719, 1.68313104, 0.60773212,
        0.81483884, 0.7915281 , 1.57465374, 1.01816741, 0.79433576],
       [0.84829992, 1.10771381, 1.41812443, 1.8392142 , 1.08313235,
        0.48310051, 0.69331833, 0.37787603, 1.57087215, 1.05137426],
       [0.54864958, 0.84292423, 1.29508498, 1.12441746, 0.22011415,
        0.4099093 , 1.14740165, 0.28284704, 1.08862975, 0.60214148],
       [1.15155327, 1.72973759, 1.72959407, 0.48783159, 0.55639635,
        0.09627787, 0.94289854, 1.82464186, 1.33749433, 0.96290947],
       [0.11297345, 0.71738787, 0.27146068, 0.84465742, 0.60052521,
        1.39991125, 1.58581247, 0.91017932, 0.7931352 , 1.44467849]])

In [25]:
np.save("saved array", Broad)

In [26]:
test = np.load("saved array.npy")
test

array([[1.55186308, 0.34749797, 1.11877719, 1.68313104, 0.60773212,
        0.81483884, 0.7915281 , 1.57465374, 1.01816741, 0.79433576],
       [0.84829992, 1.10771381, 1.41812443, 1.8392142 , 1.08313235,
        0.48310051, 0.69331833, 0.37787603, 1.57087215, 1.05137426],
       [0.54864958, 0.84292423, 1.29508498, 1.12441746, 0.22011415,
        0.4099093 , 1.14740165, 0.28284704, 1.08862975, 0.60214148],
       [1.15155327, 1.72973759, 1.72959407, 0.48783159, 0.55639635,
        0.09627787, 0.94289854, 1.82464186, 1.33749433, 0.96290947],
       [0.11297345, 0.71738787, 0.27146068, 0.84465742, 0.60052521,
        1.39991125, 1.58581247, 0.91017932, 0.7931352 , 1.44467849]])